export const COMMON_EXERCISES: string[] = [
  // Chest
  'Bench Press',
  'Incline Bench Press',
  'Decline Bench Press',
  'Dumbbell Bench Press',
  'Incline Dumbbell Press',
  'Dumbbell Fly',
  'Cable Fly',
  'Incline Cable Fly',
  'Machine Chest Press',
  'Pec Deck',
  'Push-up',
  'Wide Push-up',
  'Diamond Push-up',
  'Close-Grip Bench Press',

  // Shoulders
  'Overhead Press',
  'Dumbbell Shoulder Press',
  'Arnold Press',
  'Lateral Raise',
  'Front Raise',
  'Rear Delt Fly',
  'Face Pull',
  'Upright Row',
  'Cable Lateral Raise',
  'Machine Shoulder Press',

  // Triceps
  'Tricep Dip',
  'Tricep Pushdown',
  'Skull Crusher',
  'Overhead Tricep Extension',
  'Cable Overhead Tricep Extension',
  'Tricep Kickback',
  'Close-Grip Push-up',

  // Back
  'Pull-up',
  'Chin-up',
  'Assisted Pull-up',
  'Lat Pulldown',
  'Close-Grip Lat Pulldown',
  'Barbell Row',
  'Dumbbell Row',
  'Seated Cable Row',
  'T-Bar Row',
  'Chest-Supported Row',
  'Straight-Arm Pulldown',
  'Shrug',
  'Dumbbell Shrug',
  'Good Morning',
  'Back Extension',

  // Biceps
  'Barbell Curl',
  'Dumbbell Curl',
  'Hammer Curl',
  'Preacher Curl',
  'Incline Dumbbell Curl',
  'Cable Curl',
  'EZ Bar Curl',
  'Reverse Curl',
  'Concentration Curl',
  'Spider Curl',
  'Zottman Curl',

  // Legs
  'Squat',
  'Back Squat',
  'Front Squat',
  'Goblet Squat',
  'Sumo Squat',
  'Hack Squat',
  'Leg Press',
  'Romanian Deadlift',
  'Stiff-Leg Deadlift',
  'Leg Extension',
  'Leg Curl',
  'Lying Leg Curl',
  'Seated Leg Curl',
  'Lunge',
  'Walking Lunge',
  'Reverse Lunge',
  'Bulgarian Split Squat',
  'Hip Thrust',
  'Glute Bridge',
  'Calf Raise',
  'Seated Calf Raise',
  'Step-Up',
  'Box Squat',

  // Core
  'Plank',
  'Side Plank',
  'Crunch',
  'Sit-up',
  'Leg Raise',
  'Hanging Leg Raise',
  'Hanging Knee Raise',
  'Russian Twist',
  'Cable Crunch',
  'Ab Wheel Rollout',
  'Mountain Climber',
  'Hollow Body Hold',
  'Dead Bug',
  'Bicycle Crunch',
  'Toe Touch',
  'V-up',

  // Compound / Full Body
  'Deadlift',
  'Sumo Deadlift',
  'Trap Bar Deadlift',
  'Power Clean',
  'Clean and Press',
  'Thruster',
  'Kettlebell Swing',
  'Kettlebell Clean',
  'Kettlebell Snatch',
  'Turkish Get-up',
  'Farmer Carry',
  'Suitcase Carry',

  // Cardio / Conditioning
  'Running',
  'Treadmill',
  'Cycling',
  'Stationary Bike',
  'Rowing',
  'Elliptical',
  'Jump Rope',
  'Burpee',
  'Box Jump',
  'Broad Jump',
  'Sled Push',
  'Sled Pull',
  'Battle Ropes',
  'Stair Climber',
];
