/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/active` | `/active`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trainer` | `/trainer`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workouts` | `/workouts`; params?: Router.UnknownInputParams; } | { pathname: `/workout/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/active` | `/active`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trainer` | `/trainer`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workouts` | `/workouts`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/categories${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/active${`?${string}` | `#${string}` | ''}` | `/active${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trainer${`?${string}` | `#${string}` | ''}` | `/trainer${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workouts${`?${string}` | `#${string}` | ''}` | `/workouts${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/active` | `/active`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trainer` | `/trainer`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workouts` | `/workouts`; params?: Router.UnknownInputParams; } | `/workout/${Router.SingleRoutePart<T>}` | { pathname: `/workout/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
